name: lambda-deployment-with-github-action-test

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: [16.x, 18.x]

      - name: Install serverless globally
        run: npm install -g serverless

      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Rune e2e test
        run: npm run test:e2e

      - name: Deploy lambda function
        run: sls deploy
